(() => { "use strict";
  const STORAGE_KEY="mmPackagedRulesEnabled",OWNER="static-v1",rules=Array.isArray(globalThis.MMPackagedRules)?globalThis.MMPackagedRules:[],listeners=new Map();let enabled=true,scheduled=false;
  const route=/^https:\/\/boards\.4chan\.org\/[a-z0-9]+\/thread\/\d+(?:[/?#]|$)/u;if(!route.test(location.href))return;
  const owned=()=>[...document.querySelectorAll(`[data-mm-owner="${OWNER}"]`)];
  function remove(){for(const item of owned()){const listener=listeners.get(item);if(listener)item.removeEventListener("click",listener);listeners.delete(item);item.remove();}globalThis.MMFiniteComponents?.cleanup();}
  function apply(){scheduled=false;if(!enabled){remove();return;}globalThis.MMFiniteComponents?.mount?.();for(const rule of rules){const parents=[...document.querySelectorAll(rule.parentSelector)].slice(0,256);for(const parent of parents){const matches=[...parent.children].filter(item=>item.dataset.mmOwner===OWNER&&item.dataset.mmRule===rule.id);let item=matches.shift();for(const duplicate of matches){listeners.delete(duplicate);duplicate.remove();}if(!item){item=document.createElement(rule.tag);item.dataset.mmOwner=OWNER;item.dataset.mmRule=rule.id;const listener=event=>{event.preventDefault();if(rule.behavior!=="local-component")event.stopPropagation();if(rule.behavior==="local-component")globalThis.MMFiniteComponents?.activate(rule.component,{menuItem:item});};item.addEventListener("click",listener);listeners.set(item,listener);}const text=rule.behavior==="local-component"?globalThis.MMFiniteComponents?.label(rule.component,{menuItem:item})||rule.text:rule.text;if(item.textContent!==text)item.textContent=text;if(item.getAttribute("role")!=="menuitem")item.setAttribute("role","menuitem");if(rule.position==="first"&&parent.firstChild!==item)parent.insertBefore(item,parent.firstChild);else if(rule.position==="second"&&parent.children[1]!==item)parent.insertBefore(item,parent.children[1]||null);else if(rule.position==="last"&&parent.lastChild!==item)parent.append(item);}}}
  function schedule(){if(scheduled)return;scheduled=true;queueMicrotask(apply);}
  const observer=new MutationObserver(schedule);observer.observe(document.documentElement,{childList:true,subtree:true});
  if(chrome.storage?.local){chrome.storage.local.get([STORAGE_KEY]).then(value=>{enabled=value[STORAGE_KEY]!==false;schedule();}).catch(schedule);chrome.storage.onChanged?.addListener((changes,area)=>{if(area!=="local"||!changes[STORAGE_KEY])return;enabled=changes[STORAGE_KEY].newValue!==false;schedule();});}else schedule();
})();
